<?php
return [
    ["title" => "SETTING_FACEBOOK_URL", "type" => "text"],
    ["title" => "SETTING_TWITTER_URL", "type" => "text"],
    ["title" => "SETTING_INSTAGRAM_URL", "type" => "text"],
    ["title" => "SETTING_SEO_TITLE", "type" => "text"],
    ["title" => "SETTING_SEO_DESCRIPTION", "type" => "text"],
    ["title" => "SETTING_LOGO", "type" => "file"],
    ["title" => "SETTING_SOCIAL_SHARE_IMAGE", "type" => "file"],
    ["title" => "SETTING_PHONE", "type" => "text"],
    ["title" => "SETTING_EMAIL", "type" => "text"],
    ["title" => "SETTING_CUSTOM_HEADER_SCRIPTS", "type" => "text-area"],
    ["title" => "SETTING_CUSTOM_FOOTER_SCRIPTS", "type" => "text-area"],
    ["title" => "SETTING_ROBOTS", "type" => "text"],
    ["title" => "SETTING_RECAPTCHA_SITE_KEY", "type" => "text"],
    ["title" => "SETTING_RECAPTCHA_SECRET_KEY", "type" => "text"],
    ["title" => "SETTING_HELPERS", "type" => "text"],
    ["title" => "SETTING_YEAR_OF_EXPERIENCE", "type" => "text"],
    ["title" => "SETTING_YEAR_OF_EXPERIENCE", "type" => "text"],
    ["title" => "SETTING_HAPPY_VOLUNTEERS", "type" => "text"],
    ["title" => "SETTING_ESTABLISHMENT_YEAR", "type" => "text"],
    ["title" => "SETTING_RECAPTCHA_SECRET_KEY", "type" => "text"],
    ["title" => "SETTING_COPYRIGHT_TEXT", "value"=>"© 2021 hhfnepal.org All rights reserved.","type" => "text"],
    ["title" => "SETTING_DESTINATION_DESCRIPTION", "type" => "text-area"],
    ["title" => "SETTING_SAFETY_AND_SUPERVISION", "type" => "text-area"],
    ["title" => "SETTING_CONTACT_US_DESCRIPTION", "type" => "text-area"],
];
